language: node_js
node_js:
- '8.11'
env:
  global:
  - secure: DexwsM0r5hMn51ty/38KCdP5sIYJUrmEjEEW3O8lNakcCkOXIteQMmcb24PCX4eIa2QGwM4oQsDEDMuk+7qku0fdGa7Rl7nb+YtGuJfigC9V/oLSjG6jFrNhc5P5lIJ09RhACEOhkEpzpytx40kkh2TfB+gyig3WlT1ygsU+NP+2UDEQXZGLanMT+JuvaL1ntYrpInThFXJOk4PEfdoK/0zLAphZjBcqpm6FswXB6yIgzfhoQ5jCG9dD7DcZ2EZNXMnlQbVrojLGIOEUae6B1TBEk7RAj0erS3/DnGhyklBlZLMmgDEZkS975uuxN7I4VSUFFRIikbtVZwIs0SOUXcj0kZLQR/H6N0llar613XxDudIGIkcXFa/BrVSrJdtZ3NGz4U6bEigLD53/8xO2Zg8q/shZQNvTsXPIL7COebERGFJwY7VsJ82sCv4/R4da9i8pje2URe/SIsKTeA94yFr9PD0U0yH8B9W6oGNLE+EDXKX9r3LfFIpH+dWC680+Wt7TU1REPTHS/FR8YwGWLGl8ixKzJcOa9MkivyzYkTh7ReHGGQqenhZzJAUdjoL9UIYYz3SzSuNzPEcrRQrmAHaOqmmyhKmgrIz0+XXHkQDJXZXxrH5Labs5laLbUX9IJEbR9QSKmScvEVWhumr08NUWYgKEvH0YDR/QqYl96A0=
  - secure: AtchFU1t3IbqwhrOGBiyfBm8xBheH21XgNvEaREDfuP/DAXPRmrHt6h6fdd/5k8qf8SkDX8H5pik9R8uhyemdWjuM/g9Iw4DgFlNG3Me7VAO2qHrAMaN1cKrpehHT9a1x1o6blb88xeDUDf+6E1i24TnFEKZ34m91KCU7aXtush5yqNLthRlkyUjyAgVvVVkdwV9ChPVYWFC0fYLynbHKY7tb620OcdW/cI7jnA9L9AYdF2rxkIC4x0lwODHuRvIZYYT+YMp6WV5mQrrICy+0undq+LBjgGYPRUFyvR3W//7FREHY0LCbIsVLQpxIulqS5ybujlD45nQ4Hm9sp4Y25+lGrVU9d4FOoDp3J8i/pdjRS88tEaT1V3a5x4kSc+XUL7STocEerriRXJPAIozSnsxFc6D/KZjwobb2KaG5UO+MYUR8SrYzCNZ87IxnmswyiCC31pv1Ixpm7mzPvua6CeJlSypFkgrxSUi+CJdu4rpiEPDWSeixMtlgV+KWsab4hJJN6czCdWuFb+31x7pZfKvqwX5/dXiDH21tn0uOJvduXLEZdceHQWXbVzOZfOKSnu8dxEaYtiXNdn0zMSPNqWCPmdcbc3C7b5cnvup2jWCVfJ7jDz0hbEXe4+HMHSt5kYjIfbJVG/TP9m7q8HAo7+jf/kGM2o8QpgmDIOAr9M=
script:
- yarn run build
deploy:
- provider: npm
  email: simbo@simbo.de
  api_key: "${NPM_API_KEY}"
  on:
    tags: true
    repo: simbo/css-reset-and-normalize
    node: '8.11'
  skip_cleanup: true
- provider: pages
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
    node: '8.11'
  local-dir: css
  target-branch: gh-pages
  skip-cleanup: true
  keep-history: true
