name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 🛎  Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 📄  Read .nvmrc
        id: nvm
        run: echo "::set-output name=version::$(cat .nvmrc)"

      - name: 🛠  Setup node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '${{ steps.nvm.outputs.version }}'

      - name: 📦  Install
        run: yarn install

      - name: 👷‍♂️  Build
        run: yarn build

      - name: 👀  Check for version update
        id: version
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/css-reset-and-normalize/package.json
          static-checking: localIsNew

      - name: 📋  Get Commits since last Release
        if: steps.version.outputs.changed == 'true'
        use: simbo/changes-since-last-release-action@v1
        id: changes

      - name: 🎁  Create tag and GitHub Release
        if: steps.version.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes since ${{ steps.changes.outputs.last-tag }}:
            ${{ steps.changes.outputs.log }}

      - name: 🚚  Publish to npm
        if: steps.version.outputs.changed == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: 📝  Copy README for gh-pages
        run: cp -f README.md css/README.md

      - name: 🚚  Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: css
          CLEAN: true
